xcodeproj 'XINGAPIClient Tests'
workspace '../XNGAPIClient'
inhibit_all_warnings!

platform :ios, '7.0'
link_with 'iOS Tests'

pod 'OCMock', '~> 2.1.1'
pod 'Expecta', '~> 0.2.1'
pod 'XINGAPI', :path => '../'
pod 'OHHTTPStubs', '~> 3.0.2'
